from .nodes.gemini import IMPL_NODE_CLASS_MAPPINGS as GEMINI_CLASS_MAPPINGS
from .nodes.gemini import \
    IMPL_NODE_DISPLAY_NAME_MAPPINGS as GEMINI_DISPLAY_NAME_MAPPINGS
from .nodes.nano_banana import \
    IMPL_NODE_CLASS_MAPPINGS as NANO_BANANA_CLASS_MAPPINGS
from .nodes.nano_banana import \
    IMPL_NODE_DISPLAY_NAME_MAPPINGS as NANO_BANANA_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**GEMINI_CLASS_MAPPINGS, **NANO_BANANA_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**GEMINI_DISPLAY_NAME_MAPPINGS, **NANO_BANANA_DISPLAY_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']